{
 "title": "PGRWL: WAL Upload & Retention (Basic Counters)",
 "tags": [
  "pgrwl",
  "postgres",
  "wal",
  "upload",
  "basic"
 ],
 "panels": [
  { "title": "WAL-Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgrwl_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAL Files Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgrwl_wal_files_received_total" }
   ]
  },
  {
   "title": "WAL Files Uploaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgrwl_wal_files_uploaded_total" }
   ]
  },
  {
   "title": "WAL Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgrwl_wal_bytes_received_total" }
   ]
  },
  {
   "title": "WAL Files Deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgrwl_wal_files_deleted_total" }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Jobs Submitted",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(pgrwl_jobq_jobs_submitted_total) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Executed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(pgrwl_jobq_jobs_executed_total) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, name) (rate(pgrwl_jobq_job_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Dropped",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(pgrwl_jobq_jobs_dropped_total) by (name, reason)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}