@startuml
start

partition "Streaming Process" {
  :Receive WAL segment;
  :Finish writing;
  :Rename to <segment> (remove .partial);
}

partition "Archiver Goroutine" {
  if (Is file opened by receiver?) then (yes)
    :Read WAL from wal_receive;
    :Compress, encrypt and upload to remote storage;
    if (upload success?) then (yes)
      :Delete original WAL file;
    endif
  endif
}

stop
@enduml
