{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgrwl.backupFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgrwl.backupLabels" . | nindent 4 }}
data:
  config.yml: |
    {{- tpl (mergeOverwrite (tpl .Values.backup.config . | fromYaml) .Values.structuredConfig | toYaml) . | nindent 4 }}
{{- end }}
