---
main:
  listen_port: 7070
  directory: wals

backup:
  cron: "* * * * *"
  retention:
    enable: true
    type: time
    value: "1m"
    keep_last: 1
  walretention:
    enable: true
    receiver_addr: "pgrwl-receive:7070"

log:
  level: trace
  format: text
  add_source: true

#storage:
#  name: "local"
#  compression:
#    algo: gzip
#  encryption:
#    algo: aes-256-gcm
#    pass: qwerty123
