---
main:
  listen_port: 7070
  directory: wals

receiver:
  slot: pgrwl_v5
  #uploader:
  #  sync_interval: 10s
  #  max_concurrency: 4
  #retention:
  #  enable: true
  #  sync_interval: 10s
  #  keep_period: "30s"

dev_config:
  pprof:
    enable: true

log:
  level: trace
  format: text
  add_source: true

#storage:
#  name: "local"
#  compression:
#    algo: gzip
#  encryption:
#    algo: aes-256-gcm
#    pass: qwerty123
