services:
  pg-primary:
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    container_name: pg-primary
    restart: unless-stopped
    environment:
      TZ: "Asia/Aqtau"
    ports:
      - "15432:5432"
      - "2323:22"
    volumes:
      - pg-primary-data:/var/lib/postgresql/17/main
      - shared-data:/mnt

  pgreceivewal:
    build:
      context: .
      dockerfile: ./Dockerfile_pgreceivewal
    container_name: pgreceivewal
    environment:
      PGHOST: pg-primary
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    command: -D /mnt/wal-archive -S example_slot --no-loop
    volumes:
      - shared-data:/mnt
    restart: unless-stopped
    depends_on:
      - pg-primary

volumes:
  pg-primary-data:
  shared-data:
