services:
  pg-primary:
    image: postgres:17
    container_name: pg-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - pg-primary-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: -c max_wal_senders=10
      -c wal_keep_size=64MB
      -c listen_addresses=*
      -c log_replication_commands=on
      -c hba_file=/etc/postgresql/pg_hba.conf

  pgreceivewal:
    build:
      context: .
      dockerfile: ./Dockerfile_pgreceivewal
    container_name: pgreceivewal
    environment:
      PGHOST: pg-primary
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    command: -D /tmp/wal-archive -S example_slot
    volumes:
      - ./wals:/tmp/wal-archive
    restart: unless-stopped
    depends_on:
      - pg-primary

volumes:
  pg-primary-data:

