FROM alpine:latest

# Install packages
RUN apk update && apk add --no-cache \
    bash \
    vim \
    mc \
    tzdata

# Set timezone
ENV TZ=Asia/Aqtau

# Optional: write timezone config (makes date/time work correctly)
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Setup 'root' user
RUN echo "root:root" | chpasswd
COPY files/dotfiles/ /root

COPY bin/pgrwl /usr/local/bin/pgrwl
COPY files/configs /tmp/configs

ENTRYPOINT ["/usr/local/bin/pgrwl"]
