FROM alpine:latest

RUN apk update && apk add --no-cache bash vim mc

# Setup 'root' user
RUN echo "root:root" | chpasswd
COPY files/dotfiles/ /root

COPY bin/pgreceivewal /usr/local/bin/pgreceivewal

ENTRYPOINT ["/usr/local/bin/pgreceivewal"]
