services:
  pg-primary:
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    container_name: pg-primary
    restart: unless-stopped
    environment:
      TZ: "Asia/Aqtau"
    ports:
      - "15432:5432"
      - "2323:22"
    volumes:
      - pg-primary-data:/var/lib/postgresql/17/main
      - shared-data:/mnt
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  pgrwl:
    container_name: pgrwl
    image: quay.io/hashmap_kz/pgrwl:latest
    environment:
      TZ: "Asia/Aqtau"
      PGHOST: pg-primary
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    command: start -c /tmp/configs/config.yml -m receive
    volumes:
      - shared-data:/mnt
      - ./files/configs/config.yml:/tmp/configs/config.yml:ro
    depends_on:
      pg-primary:
        condition: service_healthy

volumes:
  pg-primary-data:
  shared-data:
