services:
  pg-primary:
    image: postgres:17
    container_name: pg-primary
    restart: unless-stopped
    environment:
      TZ: "Asia/Aqtau"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - pg-primary-data:/var/lib/postgresql/17/main
      - ./files/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: -c wal_level=replica
      -c max_wal_senders=10
      -c wal_keep_size=64MB
      -c listen_addresses=*
      -c log_replication_commands=on
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  pgrwl:
    container_name: pgrwl
    image: quay.io/hashmap_kz/pgrwl:latest
    environment:
      TZ: "Asia/Aqtau"
      PGHOST: pg-primary
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    command: start -c /tmp/configs/config.yml -m receive
    volumes:
      - ./wals:/mnt
      - ./files/configs/config.yml:/tmp/configs/config.yml:ro
    depends_on:
      pg-primary:
        condition: service_healthy

volumes:
  pg-primary-data:
